# Generated by Django 4.1 on 2022-08-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipes',
            name='hotel_Main_Img',
        ),
        migrations.AddField(
            model_name='pipes',
            name='image',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
